backend:
  name: github
  repo: Everpoint/everpoint-site
  branch: master

media_folder: static/img
public_folder: /img

collections:
  - name: "about"
    label: "Сми о нас"
    widget: "string"
    folder: "src/data/about"
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    create: true
    fields:
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "about"}
      - {label: "Заголовок", name: "title", widget: "string", pattern: ["^.{1,100}$", "Не больше 100 символов"]}
      - {label: "Дата публикации", name: "date", widget: "date"}
      - {label: "Краткое описание", name: "description", widget: "text", pattern: ["^.{1,250}$", "Не больше 250 символов"] }
      - {label: "Ссылка", name: "link", widget: "string"}
      - {label: "Логотип", name: "logo", widget: image}
      - {label: "Отображать на главной", name: "isVisible", widget: "boolean", default: false}
  - name: "pages"
    label: "Страницы"
    files:
      - file: "src/data/pages/about-page.md"
        label: "Новостная страница, родительский маршрут /about"
        name: "about-page"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "about-page"}
          - {label: "page Id", name: "id", widget: "hidden"}
          - {label: "Новостной блок /about", name: "title", widget: "string"}
      - file: "src/data/pages/contact-page.md"
        label: "Страница контактов, родительский маршрут /contacts"
        name: "contact-page"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "contact-page"}
          - {label: "page Id", name: "id", widget: "hidden"}
          - {label: "Заголовок", name: "title", widget: "string"}
          - {label: "Адрес", name: "address", widget: "string"}
          - {label: "Телефон", name: "phone", widget: "string"}
          - {label: "Email", name: "email", widget: "string"}
  - name: "vacancy"
    label: "Вакансии"
    widget: "string"
    folder: "src/data/vacancy"
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    create: true
    fields:
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "vacancy"}
      - {label: "Название вакансии", name: "vacancyName", widget: "string"}
      - {label: "Аватар", name: "avatar", widget: image}
      - {label: "Формат работы", name: "workFormat", widget: "string"}
      - {label: "Занятость", name: "employment", widget: "string"}
      - {label: "Оклад", name: "salary", widget: "string", required: false}
      - label: "Контакты"
        name: "contacts"
        widget: "object"
        fields:
          - {label: "ФИО", name: "fullName", widget: "string"}
          - {label: "Telegram", name: "telegram", widget: "string", required: false}
          - {label: "Email", name: "email", widget: "string"}
      - {label: "Ключевые навыки", name: "skills", widget: "list", required: false}
      - label: 'Блок "Что мы ждем от вас"'
        name: "expectations"
        widget: "object"
        fields:
          - {label: "Название блока", name: "expectationsTitle", widget: "string", default: "Что мы ждем от вас"}
          - {label: 'Перечень требований', name: 'requirementsList', widget: 'markdown'}
      - label: 'Блок с вложением"'
        name: "attachmentBlock"
        widget: "object"
        required: false
        fields:
          - {label: "Пояснительный текст", name: "explanatoryText", widget: "string", default: "На данную вакансию требуется выполнить тестовое задание"}
          - {label: 'Файл', name: 'file', widget: 'file'}
      - label: 'Текстовый блок "Что предлагаем взамен"'
        name: "sentence"
        widget: "object"
        fields:
          - label: "Название блока"
            name: "sentenceTitle"
            widget: "string"
            default: "Что предлагаем взамен"
          - label: 'Перечень требований'
            name: 'sentenceBody'
            widget: 'markdown'
            default: "test"
      - label: "Последний блок"
        name: "footerText"
        widget: "markdown"
        default: "Хотите у нас работать? <br /> Пишите в чат или по указанным в вакансии контактам!"

